name: Deploy Chat App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            git config --global --add safe.directory ~/chatapp-server
            cd ~/chatapp-server
            git fetch origin
            git reset --hard origin/main
            docker-compose down
            docker-compose up --build -d